name: Full ES6 floating point tests

on:
  push:
    branches:
      - main
    paths:
      - "src/rfc8785/_impl.py"
  pull_request:
    paths:
      - "src/rfc8785/_impl.py"

permissions: {}

jobs:
  test:
    strategy:
      matrix:
        python:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: download es6 test file
        run: |
          curl -L -o test/assets/es6testfile100m.txt.gz \
            https://github.com/cyberphone/json-canonicalization/releases/download/es6testfile/es6testfile100m.txt.gz

      - name: test
        run: make test INSTALL_EXTRA=test
